### ISSUE TITLE
Possible BUG: stopping higher numbered priority before it finishes

### ISSUE THREAD

**Issue by mooinglemur** [mooinglemur/zsmkit#3]
Does this still hold open the channels that it was using (assumedly wrong) or does it release them back for use by lower priorities? (intended)

**Comment by voidstar78** [comment]
Because sometimes you just want to play brief rolling snippets of a really long ZSM in the higher priority (something even longer than the BG 0 priority) :P

**Comment by mooinglemur** [comment]
The code handles this fine, as mentioned on Discord, the example ZSM where this was occurring had one set of key-down events where it just played one note, forever, while manipulating the frequency.  This is fine when the notes just play continually without interruption.  Unfortunately, if the channel is suspended and taken over by a higher priority, upon restore the channels remain keyed off until their next key down event, and for this example ZSM, there weren't any.
